"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

type Language = "en" | "zh" | "ja"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: typeof translations.en
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const translations = {
  en: {
    title: "Reimbursement Report",
    companyLogo: "Company Logo",
    basicInfo: "Basic Information",
    company: "Company",
    employeeName: "Employee Name / Ident",
    department: "Department / Account / Client",
    site: "Site",
    date: "Date",
    billableToClient: "Billable to Client?",
    clientNamePlaceholder: "Enter client name",
    travelReimbursement: "Travel Reimbursement",
    purposeOfTravel: "Purpose of Travel",
    travelPeriod: "Travel Period",
    noOfDays: "No. of Days",
    travelDestination: "Travel Destination",
    travelNote: "Note: For travel reimbursements, please attach approved TRF and boarding passes.",
    expensesBreakdown: "Expenses Breakdown (Non-Billable Expenses)",
    addExpense: "Add Row",
    addExpenseTooltip: "Add a new expense row",
    date: "Date",
    particulars: "Particulars",
    refNo: "Ref No",
    currency: "Currency",
    amountSource: "Amount (Source)",
    fxRate: "FX Rate",
    amountBilling: "Amount (Billing)",
    amountBillable: "Billable Amount",
    expenseType: "Expense Type",
    meals: "Meals",
    transportation: "Transportation & Travel",
    other: "Other",
    totalMeals: "Total Meals",
    totalTransportation: "Total Transportation",
    totalOther: "Total Other",
    grandTotal: "Grand Total",
    attachments: "Attachments",
    addAttachment: "Add File",
    addAttachmentTooltip: "Upload additional supporting documents",
    attachmentNote: "Validation: File size must be ≤ 10MB. Only PDF format allowed.",
    attachment: "Attachment",
    submittedBy: "Submitted By",
    employeeNameSignature: "Employee Name & Signature",
    signaturePlaceholder: "Type your full name",
    submit: "Submit Report",
    submitting: "Submitting...",
    requiredFieldsError: "Please fill in all required fields.",
    attachmentError: "Please ensure all attachments are valid PDF files under 10MB.",
    fileSizeError: "File size must be 10MB or less.",
    fileTypeError: "Only PDF files are allowed.",
    submitSuccess: "Form submitted successfully!",
    submitError: "Failed to submit form. Please try again.",
    particularsPlaceholder: "Description",
    refNoPlaceholder: "Ref#",
  },
  zh: {
    title: "报销报告",
    companyLogo: "公司标志",
    basicInfo: "基本信息",
    company: "公司",
    employeeName: "员工姓名/身份",
    department: "部门/账户/客户",
    site: "地点",
    date: "日期",
    billableToClient: "向客户收费？",
    clientNamePlaceholder: "输入客户名称",
    travelReimbursement: "差旅报销",
    purposeOfTravel: "出差目的",
    travelPeriod: "差旅期间",
    noOfDays: "天数",
    travelDestination: "目的地",
    travelNote: "注意：对于差旅报销，请附上已批准的TRF和登机牌。",
    expensesBreakdown: "费用明细（不可向客户收费的费用）",
    addExpense: "添加行",
    addExpenseTooltip: "添加新的费用行",
    date: "日期",
    particulars: "详情",
    refNo: "参考号",
    currency: "货币",
    amountSource: "金额（原币）",
    fxRate: "汇率",
    amountBilling: "金额（计费币）",
    amountBillable: "可收费金额",
    expenseType: "费用类型",
    meals: "餐费",
    transportation: "交通和差旅",
    other: "其他",
    totalMeals: "餐费总计",
    totalTransportation: "交通总计",
    totalOther: "其他总计",
    grandTotal: "总计",
    attachments: "附件",
    addAttachment: "添加文件",
    addAttachmentTooltip: "上传额外的支持文件",
    attachmentNote: "验证：文件大小必须≤10MB。仅允许PDF格式。",
    attachment: "附件",
    submittedBy: "提交人",
    employeeNameSignature: "员工姓名及签名",
    signaturePlaceholder: "输入您的全名",
    submit: "提交报告",
    submitting: "提交中...",
    requiredFieldsError: "请填写所有必填字段。",
    attachmentError: "请确保所有附件都是小于10MB的有效PDF文件。",
    fileSizeError: "文件大小必须为10MB或更小。",
    fileTypeError: "仅允许PDF文件。",
    submitSuccess: "表单提交成功！",
    submitError: "提交表单失败。请重试。",
    particularsPlaceholder: "描述",
    refNoPlaceholder: "参考号",
  },
  ja: {
    title: "経費精算報告書",
    companyLogo: "会社ロゴ",
    basicInfo: "基本情報",
    company: "会社",
    employeeName: "従業員名/ID",
    department: "部門/アカウント/クライアント",
    site: "サイト",
    date: "日付",
    billableToClient: "クライアントへの請求？",
    clientNamePlaceholder: "クライアント名を入力",
    travelReimbursement: "出張経費精算",
    purposeOfTravel: "出張目的",
    travelPeriod: "出張期間",
    noOfDays: "日数",
    travelDestination: "出張先",
    travelNote: "注意：出張経費精算の場合は、承認されたTRFと搭乗券を添付してください。",
    expensesBreakdown: "経費内訳（請求不可経費）",
    addExpense: "行を追加",
    addExpenseTooltip: "新しい経費行を追加",
    date: "日付",
    particulars: "詳細",
    refNo: "参照番号",
    currency: "通貨",
    amountSource: "金額（元通貨）",
    fxRate: "為替レート",
    amountBilling: "金額（請求通貨）",
    amountBillable: "請求可能金額",
    expenseType: "経費種別",
    meals: "食事",
    transportation: "交通費・旅費",
    other: "その他",
    totalMeals: "食事合計",
    totalTransportation: "交通費合計",
    totalOther: "その他合計",
    grandTotal: "総計",
    attachments: "添付ファイル",
    addAttachment: "ファイルを追加",
    addAttachmentTooltip: "追加のサポート文書をアップロード",
    attachmentNote: "検証：ファイルサイズは10MB以下である必要があります。PDF形式のみ許可されます。",
    attachment: "添付ファイル",
    submittedBy: "提出者",
    employeeNameSignature: "従業員名と署名",
    signaturePlaceholder: "フルネームを入力",
    submit: "報告書を提出",
    submitting: "送信中...",
    requiredFieldsError: "すべての必須フィールドに入力してください。",
    attachmentError: "すべての添付ファイルが10MB未満の有効なPDFファイルであることを確認してください。",
    fileSizeError: "ファイルサイズは10MB以下である必要があります。",
    fileTypeError: "PDFファイルのみ許可されます。",
    submitSuccess: "フォームが正常に送信されました！",
    submitError: "フォームの送信に失敗しました。もう一度お試しください。",
    particularsPlaceholder: "説明",
    refNoPlaceholder: "参照番号",
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const value = {
    language,
    setLanguage,
    t: translations[language],
  }

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
